### ISSUE TITLE
Informazioni sul caricamento della parte JS di Bootstrap Italia

### ISSUE THREAD

**Issue by francescozaia** [francesco-filicetti/django-bootstrap-italia#1]
Ciao @francesco-filicetti,

Innanzitutto complimenti per l'ottimo lavoro, preciso e ben documentato! E grazie per la condivisione in modalità aperta: potrà essere di sicuro molto utile anche per altri progetti.🙇

Volevo solo chiederti una cosa: mi sembra che nell'installazione di default non sia incluso il JS necessario per far funzionare completamente la libreria (in primis, i dropdown dei menu o il menu stesso in modalità "mobile"). C'è un motivo specifico per questa scelta?
Grazie!

**Comment by francesco-filicetti** [comment]
Ciao Francesco,
grazie di cuore delle tue parole e grazie di avermi segnalato il mancato import del .js.
Una pura dimenticanza.
Ho appena aggiornato la repository e il package su pypi.org.
Buon lavoro.
